const MUSIC_FACTS = [
  "Mozart wrote his first symphony at age 8.",
  "Beethoven continued composing after going completely deaf.",
  "A piano has 88 keys — 52 white and 36 black.",
  "The world's oldest known musical instrument is a 40,000-year-old bone flute.",
  "Vivaldi was a red-haired priest nicknamed 'The Red Priest.'",
  "Bach had 20 children. Four became famous composers.",
  "The shortest opera ever written lasts just 3 minutes and 34 seconds.",
  "Chopin gave only about 30 public performances in his entire life.",
  "The didgeridoo is one of the oldest instruments, dating back 1,500+ years.",
  "Liszt was so popular that fans would fight over his broken piano strings.",
  "A violin contains about 70 individual pieces of wood.",
  "The longest musical performance in history is still ongoing — John Cage's 'ORGAN²/ASLSP' will end in 2640.",
  "Paganini was so skilled, people thought he had made a deal with the devil.",
  "The word 'music' comes from the Greek 'mousike' — art of the Muses.",
  "Tchaikovsky's 1812 Overture calls for actual cannons in the score.",
  "The Beatles' 'Yesterday' is the most covered song in history with over 2,200 versions.",
  "Stradivarius violins are worth millions and no one can fully replicate their sound.",
  "Debussy hated being called an Impressionist.",
  "A typical symphony orchestra has about 100 musicians.",
  "The theremin is played without touching it — just moving hands near antennas.",
  "Handel wrote 'Messiah' in just 24 days.",
  "The human ear can distinguish about 1,400 different pitches.",
  "Ravel's 'Boléro' repeats the same melody 18 times, just getting louder.",
  "Elvis Presley never performed outside of North America.",
  "The longest concert by a single artist lasted 453 hours.",
  "Pythagoras discovered that musical intervals can be expressed as ratios.",
  "The first known piece of written music is 3,400 years old, from ancient Syria.",
  "Clara Schumann was one of the most distinguished pianists of the Romantic era.",
  "Singing releases endorphins, oxytocin, and reduces cortisol.",
  "The hurdy-gurdy is a stringed instrument played by turning a crank.",
  "Shostakovich kept a packed suitcase by his bed during Stalin's purges.",
  "A hummingbird's wings beat at a frequency that creates a musical tone.",
  "The glass harmonica was invented by Benjamin Franklin.",
  "Satie wrote a piece meant to be played 840 times in a row.",
  "Cows produce more milk when listening to slow music.",
  "The pentatonic scale sounds good no matter which notes you combine.",
  "Freddie Mercury had a four-octave vocal range.",
  "The pipe organ is the largest musical instrument.",
  "Music can help plants grow faster — experiments show they respond to vibrations.",
  "Nero didn't fiddle while Rome burned — the violin hadn't been invented yet.",
  "The shortest song ever recorded is 'You Suffer' by Napalm Death at 1.316 seconds.",
  "Rachmaninoff had enormous hands that could span 12 piano keys.",
  "The first CD ever pressed was ABBA's 'The Visitors' in 1982.",
  "Birdsong follows many of the same musical principles as human music.",
  "The saxophone was invented in the 1840s by Adolphe Sax.",
  "Some people experience 'frisson' — goosebumps from music — more than others.",
  "In space, no one can hear you play guitar. Sound needs a medium to travel.",
  "Hildegard von Bingen composed over 70 works of sacred music in the 12th century.",
];

export function getRandomFact(): string {
  return MUSIC_FACTS[Math.floor(Math.random() * MUSIC_FACTS.length)];
}
